name: Build and Push "Light" Nextcloud SMB Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */24 * * *' # every 24 hours

jobs:
  build_light:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest nextcloud:stable digest
        id: get_digest
        run: |
          set -e
          DIGEST=$(curl -s -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            "https://registry.hub.docker.com/v2/library/nextcloud/manifests/stable" \
            | jq -r '.config.digest')
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Read last stored digest
        id: read_last_digest
        run: |
          if [[ -f .base_digest_light ]]; then
            LAST_DIGEST=$(cat .base_digest_light)
          else
            LAST_DIGEST=""
          fi
          echo "last_digest=$LAST_DIGEST" >> $GITHUB_OUTPUT

      - name: Check if base image digest changed
        id: compare_digest
        run: |
          if [[ "${{ steps.get_digest.outputs.digest }}" != "${{ steps.read_last_digest.outputs.last_digest }}" ]]; then
            echo "Digest changed"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "Digest not changed"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.compare_digest.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: steps.compare_digest.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push "light" Docker image
        if: steps.compare_digest.outputs.changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.light
          push: true
          tags: ptabi/nxtcld-smb:light

      - name: Save updated digest
        if: steps.compare_digest.outputs.changed == 'true'
        run: echo "${{ steps.get_digest.outputs.digest }}" > .base_digest_light

      - name: Commit digest update
        if: steps.compare_digest.outputs.changed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .base_digest_light
          git commit -m "Update base digest for nextcloud:stable"
          git push
