name: Ignore Workflow Changes

on:
  push:
    paths:
      - ".github/workflows/nextcloud-update.yml"

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow updated, but rebuild not triggered"
