name: Rebuild and Push Custom Nextcloud

on:
  repository_dispatch:
    types: [nextcloud_update]

jobs:
  rebuild:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ptabi/nxtcld-smb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Чтобы не пересобирать образ при изменении workflow файла, исключаем его из контекста
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull latest nextcloud
        run: docker pull nextcloud:latest

      - name: Build custom image with cache
        run: |
          docker build \
            --cache-from $IMAGE_NAME:latest \
            --build-arg CACHEBUST=$(date +%s) \
            -t $IMAGE_NAME:latest .

      - name: Push image to Docker Hub
        run: |
          docker push $IMAGE_NAME:latest
