name: Rebuild and Push Custom Nextcloud

on:
  repository_dispatch:
    types: [nextcloud_update]

jobs:
  rebuild:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ptabi/nxtcld-smb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull latest Nextcloud image
        run: docker pull nextcloud:latest

      - name: Pull previously built custom image (if any)
        run: docker pull $IMAGE_NAME:latest || true

      - name: Build custom image using cache
        run: |
          docker build \
            --cache-from=type=registry,ref=$IMAGE_NAME:latest \
            --build-arg CACHEBUST=$(date +%s) \
            -t $IMAGE_NAME:latest .

      - name: Push image to Docker Hub
        run: docker push $IMAGE_NAME:latest
